import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { TrackingProvider } from "../../context/TrackingContext";
import {NavBar, Footer} from "./_components";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TrackingProvider>
          <NavBar />
          <main>{children}</main>
        </TrackingProvider>
        <Footer />
      </body>
    </html>
  );
}
